### ISSUE TITLE
Add momentum effect to wheels

### ISSUE THREAD

**Issue by Brandon028** [cse110-sp23-group20/fortune-teller#42]
when scrolling the wheels and suddenly stop scrolling, we want to add a momentum effect that the wheels slowly keeps turning in the same direction for a little bit.

**Comment by ohuynh21** [comment]
The wheels have had a momentum effect of sorts since the beginning. When we stop scrolling and remove the cursor from the wheel it will slowly round itself to the nearest zodiac sign. imo if we add the momentum effect you are suggesting it might make it harder for the user to align their zodiac wheels since they'd have to account for the momentum. So while it would be cool i think it might break user expectations.
